# 1 Sprint 8. First draft of filmorate app
farukshin-n/java-filmorate pull request #2
Opened 2022-06-30 14:18 UTC by farukshin-n

2022-07-01 12:15 UTC, alexache requested changes
Работа очень хорошая!

2022-07-01 12:15 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (film.getName().isBlank()) {
Эти проверки лучше вынести в отдельный метод, чтобы код не будблировался на создании/обновлении

2022-07-01 12:15 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (films.containsValue(film)) {
Такая проверка довольно затратная и не требовалась по ТЗ.
К тому же, мне кажется, она не сработает на дубли, ведь id тоже будет использовано в сравнении?

2022-07-01 12:15 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        if (user.getEmail().isBlank() || !user.getEmail().contains("@")) {
Такое же комментарий про то, что проверки стоит вынести в отдельный метод.

2022-07-01 12:15 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +public class Film {
Часть проверок можно было бы перенести на аннотации этих классов

2022-07-01 15:57 UTC, farukshin-n commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (film.getName().isBlank()) {
Сделал.

2022-07-01 15:58 UTC, farukshin-n commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (films.containsValue(film)) {
Да, всё верно, убрал.

2022-07-01 15:59 UTC, farukshin-n commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +public class Film {
Перенёс частично (аннотацию @Past для даты рождения не стал использовать, так как ругался постман и не проходил тесты).

2022-07-02 18:53 UTC, alexache approved these changes
Все ок

2022-07-04 06:24 UTC, merged