Controllers films users
farukshin-n/java-filmorate pull request #3
Opened 2022-08-02 17:41 UTC by farukshin-n

2022-08-03 10:51 UTC, alexache requested changes
Работа хорошая, но есть много кастинга интерфейсов до конкретной реалзации, что очень плохо и теряет смысл использования интерфейсов

2022-08-03 10:51 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private final FilmStorage storage;
В идеале здесь не должно быть объекта стораджа. Вся работа с данными должна идти через вызовы в сервис, который уже может использовать сторадж

2022-08-03 10:51 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        return storage.createFilm(film);
Должен быть вызов сервиса вместо стораджа

2022-08-03 10:51 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        return ((InMemoryFilmStorage) storage).getFilmList();
Помимо моего комментария о том, что сторадж не должен использоваться в контроллере - такой кастинг на конкретную имплементацию "красный" флаг, что что-то здесь не ладно с интерфейсом. Почему не вынести гет метод в интерфейс?

2022-08-03 10:51 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    private final UserStorage storage;
Такой же комментарий, как и для фильм контроллера, сторадж не должен использоваться

2022-08-03 10:51 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        return ((InMemoryUserStorage) storage).getUser(id);
Похожий комментарий с тем, что в фильм контроллере - не должно быть кастинга на конкретную имплементацию

2022-08-03 10:51 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Film film = ((InMemoryFilmStorage) storage).getFilm(filmId);
Не должно быть кастинга на конкретную имплементацию

2022-08-03 10:51 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        InMemoryUserStorage userStorage = (InMemoryUserStorage) storage;
Конкретная реализация не должна использоваться, только интерфейс

2022-08-04 12:54 UTC, farukshin-n commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private final FilmStorage storage;
Поправил

2022-08-04 12:54 UTC, farukshin-n commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        return storage.createFilm(film);
Поправил

2022-08-04 12:55 UTC, farukshin-n commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        return ((InMemoryFilmStorage) storage).getFilmList();
Поправил (часто не до конца понимаю, где ТЗ ограничивает меня в изменении интерфейса, а где нет)

2022-08-04 12:55 UTC, farukshin-n commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        return ((InMemoryUserStorage) storage).getUser(id);
Поправил

2022-08-05 11:57 UTC, alexache approved these changes
Я бы еще немного поменял сервис, но это уже  не так критично - можно поменять к следующему спринту

2022-08-05 11:57 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        return service.getStorage().createFilm(film);
Я имел в виду немного другое - нужен такой метод на стороне сервиса, а не получения ссылки на сторадж через сервис. Т.е. у сервиса должен быть метод createFilm()

2022-08-05 13:02 UTC, farukshin-n commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        return service.getStorage().createFilm(film);
Понял, поправил это тоже.

2022-08-05 13:02 UTC, merged