Add database-first attempt
farukshin-n/java-filmorate pull request #4
Opened 2022-08-14 17:40 UTC by farukshin-n

2022-08-15 15:00 UTC, alexache requested changes
Комментарии распишу в трекере

2022-08-15 15:00 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final Long ratingMPA;
Мне кажется тут будет требоваться называние рейтинга, а не ее айди

2022-08-15 15:00 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controllers/MpaController.java
> +    @Autowired
Мне кажется @Autowired тут не обязателен, спринг справится с выставлением зависимости через конструктор

2022-08-15 15:00 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final Long ratingMPA;
Мне кажется тут будет требоваться называние рейтинга, а не ее айди

2022-08-15 15:00 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storages/interfaces/UserStorage.java
> +    public User createUser(User user) throws UserNotFoundException;
А откуда может быть UserNotFoundException на создании юзера?

2022-08-15 15:00 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storages/interfaces/UserStorage.java
>      public void deleteUser(User user);
В интерфейсах не нужно дополнительно указывать модификатор public, он считается по умолчанию

2022-08-15 15:00 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storages/interfaces/MpaStorage.java
> +    public List<Mpa> getMpaList();
В других интерфейсах тот же комментарий - public не нужен у методов в интерфейсах

2022-08-15 15:00 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/storages/dao/FilmDbStorageTest.java
> +package ru.yandex.practicum.filmorate.storages.dao;public class FilmDbStorageTest {
Для чего эти пустые тест классы?

2022-08-15 15:00 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storages/dao/FilmDbStorage.java
> +        String sqlQuery = "select f.film_id, f.name, f.description, m.mpa_name, f.release_date, f.duration " +
genre тоже желательно джоинить одним запросом

2022-08-16 22:25 UTC, farukshin-n commented on src/test/java/ru/yandex/practicum/filmorate/storages/dao/FilmDbStorageTest.java
> +package ru.yandex.practicum.filmorate.storages.dao;public class FilmDbStorageTest {
Это я продолбался с гитом, теперь не пустые

2022-08-16 22:25 UTC, farukshin-n commented on src/main/java/ru/yandex/practicum/filmorate/storages/dao/FilmDbStorage.java
> +        String sqlQuery = "select f.film_id, f.name, f.description, m.mpa_name, f.release_date, f.duration " +
Сделал

2022-08-25 19:34 UTC, alexache approved these changes

2022-08-25 19:34 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    final LocalDate CHECK_DATE = LocalDate.of(1895, 12, 28);
Не хватает модификатора доступа

2022-08-25 19:34 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	private final
Выглядит странно, а это компилируется?

2022-08-25 20:26 UTC, merged